[CSL-1763] Add support for type in tasks
Constructor-io/constructorio-java pull request #106
Opened 2022-11-03 22:38 UTC by stanlp1

Adjusted test for start and end date to use last 30 days instead of hard coded date.

2022-11-04 00:18 UTC, jjl014 requested changes
Nice! The code looks good to me, but it looks like there are 2 failing tests. Might be unrelated to your changes, but we should fix them 👍 

```
newShouldReturnTaskRequestWithDefaults(io.constructor.client.AllTasksRequestTest): expected:<20> but was:<0>
settersShouldSet(io.constructor.client.AllTasksRequestTest): expected:<20> but was:<0>
```

2022-11-04 00:18 UTC, jjl014 commented on constructorio-client/src/main/java/io/constructor/client/TaskRequest.java
> -import java.io.File;
Nice! 😄

2022-11-04 00:18 UTC, jjl014 commented on constructorio-client/src/test/java/io/constructor/client/ConstructorIOTasksTest.java
> +        LocalDate endDate = LocalDate.now();
Love this change!

2022-11-11 00:16 UTC, jjl014 reviewed
Thanks for fixing the tests. Not sure what happened or something in the endpoint changed, but it looks like more tests are failing now (different tests). o_O

```
TaskRequestWithInvalidApiKeyShouldError(io.constructor.client.ConstructorIOTaskTest): (..)

TaskAsJSONRequestWithInvalidApiKeyShouldError(io.constructor.client.ConstructorIOTaskTest): (..)

AllTasksShouldReturnErrorWithInvalidApiKey(io.constructor.client.ConstructorIOTasksTest): (..)

AllTasksAsJSONShouldReturnErrorWithInvalidApiKey(io.constructor.client.ConstructorIOTasksTest): (..)
  ```

2022-11-11 00:20 UTC, stanlp1 commented
Weirdly things still pass for me. Could it be you got rate limited for those times?

2022-11-14 19:59 UTC, jjl014 approved these changes
Lgtm! 🚀

2022-11-17 20:54 UTC, merged