[Csl-985] java sdk add support for http configs
Constructor-io/constructorio-java pull request #77
Opened 2022-02-23 00:20 UTC by stanlp1

2022-02-23 00:29 UTC, jjl014 reviewed
Looking good so far, left some comments. 👍

2022-02-23 00:29 UTC, jjl014 commented on constructorio-client/src/main/java/io/constructor/client/ConstructorIO.java
> +    public static void configHttpClient(HttpClientConfig config) {
Can we change this to `setHttpClientConfig`?

2022-02-23 00:29 UTC, jjl014 commented on constructorio-client/src/main/java/io/constructor/client/ConstructorIO.java
> +    public static void setClient(OkHttpClient newClient) {
Can we change this to `setOkHttpClient` and update the different places where it's used?

We should also update the param to specify OkHttpClient (i.e. `newOkHttpClient the OkHttpClient to use by all instances` or something) 🤔

2022-02-23 00:29 UTC, jjl014 commented on constructorio-client/src/main/java/io/constructor/client/ConstructorIO.java
> +            ConnectionPool pool = new ConnectionPool(maxIdle == null ? 5 : maxIdle, keepAlive == null ? 5l : maxIdle, TimeUnit.MILLISECONDS);
What is `5l` (5 L) ?

2022-02-23 00:31 UTC, jjl014 commented on constructorio-client/src/main/java/io/constructor/client/ConstructorIO.java
> +    public static OkHttpClient getClient() {
`getHttpClient` ? 🤔

2022-02-23 01:11 UTC, rubikzube commented
We can haz tests around setting the client and setting the client configuration>

2022-02-23 20:43 UTC, rubikzube requested changes

2022-02-23 20:43 UTC, rubikzube commented on constructorio-client/src/test/java/io/constructor/client/ConstructorIOHttpClientConfigTest.java
> +    public void nullConfigVariablesDoNotGetConfigured() {
Maybe `setHttpClientConfigWithEmptyConfigShouldReturnDefaults`?

2022-02-23 20:43 UTC, rubikzube commented on constructorio-client/src/main/java/io/constructor/client/HttpClientConfig.java
> +    private Integer connPoolMaxIdleConnections;
Maybe don't abbreviate `conn` in general

2022-02-23 20:43 UTC, rubikzube commented on constructorio-client/src/main/java/io/constructor/client/HttpClientConfig.java
> +        this.readTimeout = null;
Can we set these to common defaults instead of null?

2022-02-24 01:39 UTC, rubikzube commented
@stanlp1 : are the defaults in the config the okhttp defaults?

2022-02-24 01:44 UTC, stanlp1 commented
> @stanlp1 : are the defaults in the config the okhttp defaults?

All the defaults here should be the okhttp defaults with the exception of readtimeout and writetimeout. I set those to be the times that we use in the default constructor client if they don't config anything. So if they don't change anything here this should be identical to the default constructor settings.

2022-02-24 18:12 UTC, rubikzube approved these changes

2022-02-25 21:25 UTC, merged